### ISSUE TITLE
Exit (ctrl+q) doesn't actually exit the window

### ISSUE THREAD

**Issue by hasufell** [sakhnik/nvim-ui#33]
Hi, I hope you're doing well.

----

My problem:

If I open an empty nvim-ui window, I have to do this to exit:

1. Ctrl+q -> now it shows "end of file" in the window title and no vim keys work anymore... I suspect this simply "maps" to `:q`
2. I have to instruct my window manager i3 to "force close" the window (via Ctrl-x), not sure if this sends a signal to the application

If I just press Ctrl+q several times, the window will not close. If I press Ctrl-x several times, it won't close either. This is rather confusing.

**Comment by sakhnik** [comment]
Hi! That's actually how it's programmed by design. If you press and release `<alt>`, the menu will be displayed to allow you either to spawn a new instance or to connect to a remote instance of Neovim.
If you just close the application window, it's resurrected as long as the editing session is still alive.

**Comment by sakhnik** [comment]
I've just added a hint to the window title on how to show the menu
